### ISSUE TITLE
Mint NFTs on StarGaze testnet

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/MageNFT#11]
# I. Task description
Mint NFTs on stargaze
https://github.com/public-awesome/stargaze-contracts/tree/main/contracts/sg721

# II. Task timeline
Specify timeline if exists

# III. Task deliverables
NFTs on stargaze

# IV. Task goals 
goals that this task needs to achieve

- [x]  NFTs on stargaze testnet
- [x] Randomized NFTs mint on stargaze launchpad ?
- [x] Tool for auto generating metadata file for n traits with n values

**Comment by nghuyenthevinh2000** [comment]
@chinhnotional 
please write your progress to here

**Comment by chinhnotional** [comment]
Yes, i will do

**Comment by hieuvubk** [comment]
https://big-bang.publicawesome.dev/launchpad/stars1l8aslnwdstgluynr8apllfuqelcr55l0us83y874l5l37akfzhaqp6wsru?fbclid=IwAR0LzcOv68kuwFrCyb5r9I51juUv779muEFE_OzAjJuCRNR6K8BMPpV_oew
Deploy my film NFT collection on big-bang-1 testnet
Hehe let mint to own this picture

**Comment by hieuvubk** [comment]
Updated pull request

**Comment by nghuyenthevinh2000** [comment]
A tool for auto generating metadata for a picture means that such tool needs to know what trait's value a picture contains. 
Because of the above, change to generating image source code is required to export trait's values as metadata

**Comment by hieuvubk** [comment]
can u give me trait types and their value for genesis metadata. Almost done for the tools

**Comment by nghuyenthevinh2000** [comment]
you can find traits in generative-art-tools

**Comment by nghuyenthevinh2000** [comment]
a feature that we intent to give to our clients is changable image in NFTs after minting.

This feature is for upgrading NFTs after minted.

Please refer to this issue on how to do this: https://github.com/notional-labs/MageNFT/issues/9#issue-1157995497

**Comment by hieuvubk** [comment]
Tools for generating images, metadata and creating collection on Stargaze is already
