### ISSUE TITLE
Mint cw20 mage token on Juno testnet

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/MageNFT#12]
# I. Task description
Mint cw20 mage token on Juno

# II. Task timeline
Specify timeline if exists

# III. Task deliverables
What deliverables do this task need to deliver?

# IV. Task goals 
goals that this task needs to achieve

- [x]  cw20 token on juno testnet

**Comment by nghuyenthevinh2000** [comment]
@hieuvubk 
please write your progress to here

**Comment by hieuvubk** [comment]
Minted on juno local node, next => testnet uni-2

**Comment by nghuyenthevinh2000** [comment]
you can get Juno uni-2 faucet from this discord channel

https://discord.gg/kdTdC6WW

![Uploading Screenshot from 2022-03-14 20-10-34.png…]()

**Comment by hieuvubk** [comment]
Deployed Mage Token on uni-2 testnet. 
Contract address: juno1hthjpmmjdeev6hkgvfzve0r2kvel5ca3ecr3x6y5t5r24xl4jprsy06v5d
I will update script soon

**Comment by hieuvubk** [comment]
Updated scripts

**Comment by nghuyenthevinh2000** [comment]
![Screenshot from 2022-03-15 23-31-18](https://user-images.githubusercontent.com/23058164/158426160-b9b06355-3b6a-4583-9981-d3bf52d50dcc.png)

**Comment by nghuyenthevinh2000** [comment]
@nghuyenthevinh2000 
ccan you show me picture of balances of minted tokens

**Comment by nghuyenthevinh2000** [comment]
juno testnet node:
https://rpc.uni.junonetwork.io:443

**Comment by nghuyenthevinh2000** [comment]
![Screenshot from 2022-03-15 23-42-49](https://user-images.githubusercontent.com/23058164/158428353-49fe9807-d58f-4ea8-be0f-42ba3debe6c7.png)
