### ISSUE TITLE
picture generated will be pushed directly to ipfs

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/MageNFT#24]
# I. Task description
Due to 1000 pics generated locally will have a total size of 530 MB. 10000 pics will be nearly 6gb. A too huge size to be moved around.

It is best to create an options in generative-art-nft/nft.py for user to choose to push generated pic directly to ipfs or local save.

- option 1: local save: generated pic on local save is for testing
- option 2: ipfs: generated pic on ipfs is for distribution

# II. Task timeline

# III. Task deliverables
What deliverables do this task need to deliver?

# IV. Task goals 
goals that this task needs to achieve

- [x] every picture generated will be pushed directly to ipfs.

**Comment by hieuvubk** [comment]
No need to move around, generated pictures will be save locally. If user worry about size, we will delete all in local after pushing to ipfs

**Comment by nghuyenthevinh2000** [comment]
Ok
