### ISSUE TITLE
Generate MageNFT pics

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/MageNFT#40]
# I. Task description
https://drive.google.com/drive/folders/1tCaPAJ2GGYburh8AX4p6MAHOEB3k48MF?fbclid=IwAR02wO564h-7-J9l4j9SDg7to_24ttLtpWyxmY2fywoQ707XvvQwhOQ8TtI

1. basketball: 1000 NFTs
2. hockey: 1000 NFTs
3. knight: 1000 NFTs
4. mage: 1000 NFTs

total: 4000 NFTs

tool for generation is here: https://github.com/notional-labs/MageNFT/tree/main/generative-art-nft

# II. Task timeline
Specify timeline if exists

# III. Task deliverables
What deliverables do this task need to deliver?

# IV. Task goals 
goals that this task needs to achieve

- [x]  Mint successfully 4000 NFTs

**Comment by Jammyaa** [comment]
Mint NFT log
8/4/2022
1.Basketball 1000 NFT (5 trait categories) (Done)
Thứ tự lắp: BG -> Left -> Body -> Item -> Right
*Black 500 NFT:
Tổng số lượng NFT có thể mint: 4 * 7 * 14 * 46 * 5 = 90160 (cái)
Tạo ra 502 image (2 trùng) => 500
*White 500 NFT:
Tổng số lượng NFT có thể mint: 4 * 5 * 7 * 46 * 5 = 32200 (cái)
Tạo ra 506 image (6 trùng) => 500
2. Hockey 1000 NFT (5 trait categories) (Done)
Thứ tự lắp: BG -> Left -> Body -> Item -> Right
*White 500 NFT:
Tổng số lượng NFT có thể mint: 4 * 9 * 30 * 9 * 9 = 87480 (cái)
Tạo ra 501 image (1 trùng) => 500
*Red 500 NFT:
Tổng số lượng NFT có thể mint: 4 * 9 * 24 * 9 * 9 = 69984 (cái)
Tạo ra 501 image (1 trùng) => 500
3. Knight 1000 NFT (6 trait categories) (Done)
Thứ tự lắp: BG -> Left -> Body -> Head -> Item -> Right
*Silver 334 NFT:
Tổng số lượng NFT có thể mint: 5 * 3 * 3 * 4 * 11 * 4 = 7920 (cái)
Tạo ra 339 image (5 trùng) => 334
*Black 333 NFT:
Tổng số lượng NFT có thể mint: 5 * 3 * 3 * 4 * 11 * 4 = 7920 (cái)
Tạo ra 340 image (7 trùng) => 333
*Gold 333 NFT:
Tổng số lượng NFT có thể mint: 5 * 3 * 3 * 4 * 11 * 4 = 7920 (cái)
Tạo ra 340 image (7 trùng) => 333
4. Mage 1000 NFT (6 trait categories) (Done)
Thứ tự lắp: BG -> Left -> Body -> Hat -> Item -> Right
Cần mint 1000 NFT
Tổng số lượng NFT có thể mint: 6 * 20 * 24 * 20 * 15 * 17 = 14688000 (cái)
Tạo ra 1000 image (0 trùng) => 1000
